title: "hqc.io"
site_name: "Cẩm Huỳnh"
email: "huynhquancam@gmail.com"
author: "Cẩm Huỳnh"
description: >
  Cẩm Huỳnh's personal website and random writings about programming, web development, and other stuff that interests his life.

# Serve settings
baseurl: ""
url: "https://hqc.io"
image_url: "https://c3.staticflickr.com/9/8583/28318985330_8f464b5a12_b.jpg"
profile_photo: "/assets/images/avatar.png"

# Build settings
markdown: kramdown
destination: "_site"
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
paginate: 5
paginate_path: "/essays/page/:num"

# SASS settings
sass:
  style: compressed
  sass_dir: _sass

gems:
  - bourbon
  - jekyll-paginate

defaults:
  -
    scope:
      path: ""
    values:
      author: "Cẩm Huỳnh"
      email: "huynhquancam@gmail.com"
      locale: "en_US"

# Extra settings
extras:
  handler:
    global: qcam
    github: qcam
    twitter: __qcam
    reddit: qqcam
